### ISSUE TITLE
Unable to find sbops string!

### ISSUE THREAD

**Issue by TRANTUAN-PC** [plooshi/KPlooshFinder#5]
+ ./tools/Windows/KPlooshFinder1 2_ssh_ramdisk/temp_files/kcache.raw 2_ssh_ramdisk/temp_files/kcache.patched
Starting KPlooshFinder
patch_apfs_mount: Found APFS mount
patch_trustcache_old: Found trustcache
patch_amfi_execve_tail: Found AMFI execve hook
patch_amfi_mac_syscall: Found AMFI mac_syscall
patch_amfi_sha1: Found AMFI hashtype check
patch_vnode_lookup: Found vnode_lookup
mach_traps_patch: Found mach traps
mach_traps_patch: Found tfp0
Unable to find sbops string!

**Comment by TRANTUAN-PC** [comment]
KplooshFinder stuck at "Unable to find sbops string!" on Windows.
Any solution to this problem,sir?

**Comment by mast3rz3ro** [comment]
Hi,

The memmem implementation I included in my fork is not a 100% replacement for the original function even the author of this implementation has already cleared that so it's expected to see like these errors since when you run it.

A solution for this would be to improve or write another implementation for memmem or even maybe to use another library.
